language: julia
services:
  - mysql
os:
  - osx
  - linux
julia:
  - 0.5
  - 0.6
before_script:
  - export OLD_PATH=$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mysql_config --libs | cut -d ' ' -f1 | sed 's/-L//'`
after_script:
  - export LD_LIBRARY_PATH=$OLD_PATH
  - unset OLD_PATH
