language: julia
os:
  - osx
  - linux
services:
  - mysql
julia:
  - 0.4
  - 0.5
  - nightly
before_script:
  - echo $PWD
  - export OLD_PATH=$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mariadb_config --libs | cut -d ' ' -f1 | sed 's/-L//'`
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MySQL"); if ENV["TRAVIS_OS_NAME"] == "osx" run(`$(Pkg.dir())/Homebrew/deps/usr/bin/mysql.server start`) end; Pkg.test("MySQL")'
after_script:
  - export LD_LIBRARY_PATH=$OLD_PATH
  - unset OLD_PATH
