# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

services:
 - mysql

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

julia:
  - 1.3
  - nightly

env:
  - JULIA_PROJECT="@."

matrix:
  exclude:
    - os: osx
      arch: x86
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
   - julia -e 'ENV["TRAVIS_JULIA_VERSION"] == "1.3" && ENV["TRAVIS_OS_NAME"] != "linux" && exit(); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
