language: julia
julia:
  - 0.4
  - release
before_script:
  - export OLD_PATH=$LD_LIBRARY_PATH
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`mariadb_config --libs | cut -d ' ' -f1 | sed 's/-L//'`
after_script:
  - export LD_LIBRARY_PATH=$OLD_PATH
  - unset OLD_PATH