version: "3.9"
name: "mysqljl-test"
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-u",
          "root",
          "-p''",
          "--silent",
          "--execute",
          "SELECT 1;",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app
networks:
  app:
    driver: bridge
